### ISSUE TITLE
Ensure data is updated on each visit to catalogue

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#122] opened 2020-11-17 09:50 UTC
The punctum books cover image URLs don't display in the Catalog overview or inside the Works view
<img width="1468" alt="Screenshot 2020-11-17 at 10 49 38" src="https://user-images.githubusercontent.com/20144127/99374209-a6139600-28c2-11eb-8959-aa1bc88349f4.png">
<img width="1409" alt="Screenshot 2020-11-17 at 10 49 53" src="https://user-images.githubusercontent.com/20144127/99374216-a744c300-28c2-11eb-9a6d-2b268a1f0e7f.png">

**Comment by ja573** [comment] 2020-11-17 11:12
The first case has to do with data caching.

1. Visit catalogue (no cover displayed)
2. Add cover to book
3. Visit catalogue (no cover displayed

Data in the catalogue is queried in (1) and remains there as it is, i.e. catalogue in (3) is the exact same copy of catalogue in (1). To update the data one must either refresh the page or do a query in-page.

I'll need to look into streamlining data load. I've been trying to minimise the amount of API queries, but we obviously need a mechanism to reload the data in the catalogue automatically.

**Comment by ja573** [comment] 2020-11-17 11:17
The second screenshot seems to be a different issue, though I'm not entirely sure what it might be. The cover URL seems correct, it is the same that I currently see on Thoth (where the image does load), however the cover display shows that it has not been able to load the image at the time of adding the URL. This can be caused by many things. If reloading the page fixes the issue then it'll mean that the request to fetch the image failed when it was added (most likely due to a connection issue).

**Comment by ja573** [comment] 2021-06-18 10:55
This seems to have been fixed in v0.3

**Closed by ja573** 2021-06-18 10:55 UTC
Labels: bug
