### ISSUE TITLE
Adding a new Epub Publication with URL but no ISBN creates Paperback

### ISSUE THREAD

**Issue by vincentwj** [thoth-pub/thoth#119] opened 2020-11-16 16:47 UTC
Adding an Epub as Publication to an existing Work without ISBN but with URL created a Paperback.

To replicate error:
* Work https://staging.thoth.openbookpublishers.com/admin/work/f2a2626b-4029-4e43-bb84-7b3cacf61b23
* Add Pubication
* Select Epub
* add URL https://cloud.punctumbooks.com/s/xfqNcAxNPQPsTYd
* Click Add Publication

A new Paperback, not new Epub publication has been created.

**Comment by vincentwj** [comment] 2020-11-16 16:48
I was eventually able to create an Epub publication by deleting the Paperback, creating a fake new Paperback publication, deleting that one, and then creating a new Epub publication

**Comment by ja573** [comment] 2020-11-17 12:06
I think this may have to do with certain properties not being refreshed in the form after using it. I'll need to investigate a bit more, but so far I'm not able to recreate the issue

**Comment by ja573** [comment] 2020-11-17 12:14
potentially linked to #118

**Comment by vincentwj** [comment] 2020-11-17 14:15
Ok! In any case I found a workaround, so we'll see if it persists with future upgrades.

**Comment by ja573** [comment] 2020-11-26 09:53
Closing this for now. Let's reopen if the problem is still there

**Closed by ja573** 2020-11-26 09:53 UTC
Labels: bug
